name         'thomasvandoren-etckeeper'
version      '0.0.8'
summary      'Install and configure etckeeper using git.'
description  'Install and configure etckeeper using git.'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-etckeeper'
